# E2E Labels when source files are changes
Settings:
  - "openmetadata-ui/**/*setting*"

DataAssets:
  - "openmetadata-ui/**/*database*"
  - "openmetadata-ui/**/*table*"
  - "openmetadata-ui/**/*topic*"
  - "openmetadata-ui/**/*dashboard*"
  - "openmetadata-ui/**/*pipeline*"
  - "openmetadata-ui/**/*mlmodel*"
  - "openmetadata-ui/**/*container*"
  - "openmetadata-ui/**/*serachindex*"
  - "openmetadata-ui/**/*task*"
  - "openmetadata-ui/**/*search*"
  - "openmetadata-ui/**/*mydata*"
  - "openmetadata-ui/**/*explore*"

Governance:
  - "openmetadata-ui/**/*glossary*"
  - "openmetadata-ui/**/*tag*"
  - "openmetadata-ui/**/*domain*"

Observability:
  - "openmetadata-ui/**/*alert*"
  - "openmetadata-ui/**/*incidentmanager*"
  - "openmetadata-ui/**/*metric*"
  - "openmetadata-ui/**/*dataquality*"
  - "openmetadata-ui/**/*datainsight*"
  - "openmetadata-ui/**/*observability*"

Integration:
  - "openmetadata-ui/**/*integration*"
  - "openmetadata-ui/**/*ingestion*"
  - "openmetadata-ui/**/*service*"
